# Dockerfile for service1
FROM node:latest

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
#COPY package*.json ./
COPY package.json package1.json

# Install npm dependencies
#RUN npm install

# Copy the rest of the application files
#COPY . .

# Your other Dockerfile commands go here...

# Start the application
#CMD ["npm", "start"]
