name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      env:
        DOCKER_CONFIG: ${{ secrets.DOCKER_CONFIG_JSON }}
      run: |
        mkdir -p $HOME/.docker
        echo "$DOCKER_CONFIG" > $HOME/.docker/config.json

    - name: Build and push service1 Docker image
      env:
        DOCKERHUB_REPO: giridharpatnaik183/assignment5
        DOCKER_IMAGE_TAG: service1
      working-directory: service1  # Set the working directory to the location of Dockerfile for service1
      run: |
        docker build -t $DOCKERHUB_REPO:$DOCKER_IMAGE_TAG .
        docker push $DOCKERHUB_REPO:$DOCKER_IMAGE_TAG

    - name: Build and push service2 Docker image
      env:
        DOCKERHUB_REPO: giridharpatnaik183/assignment5
        DOCKER_IMAGE_TAG: service2
      working-directory: service2  # Set the working directory to the location of Dockerfile for service2
      run: |
        docker build -t $DOCKERHUB_REPO:$DOCKER_IMAGE_TAG .
        docker push $DOCKERHUB_REPO:$DOCKER_IMAGE_TAG
